#  Copyright © 2024 Tobias Erbsland https://erbsland.dev/ and EducateIT GmbH https://educateit.ch/
#  According to the copyright terms specified in the file "COPYRIGHT.md".
#  SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 5.0.6 on 2024-06-12 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRunner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=32)),
                ("language_code", models.CharField(max_length=32)),
                ("success_url", models.CharField(blank=True, default="", max_length=250)),
                ("failure_url", models.CharField(blank=True, default="", max_length=250)),
                ("stopped_url", models.CharField(blank=True, default="", max_length=250)),
                (
                    "status",
                    models.SmallIntegerField(choices=[(0, "Created"), (1, "Running"), (2, "Finished")], default=0),
                ),
                (
                    "result",
                    models.SmallIntegerField(
                        choices=[(0, "None"), (1, "Success"), (2, "Failure"), (3, "Stopped")], default=0
                    ),
                ),
                ("input_data", models.JSONField()),
                ("status_fields", models.JSONField()),
                ("output_data", models.JSONField(null=True)),
                ("stop_requested", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                (
                    "task_runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="tasks", to="tasks.taskrunner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "indexes": [
                    models.Index(fields=["task_runner"], name="task_task_runner_idx"),
                    models.Index(fields=["owner"], name="task_owner_idx"),
                    models.Index(fields=["status"], name="task_status_idx"),
                ],
            },
        ),
    ]
